UB-ES-2020-A/Grup-ES

backend/resources/books.py, backend/tests/test_AM_3.py
Implementad l'endpoint delete per al llibre. #11
=> US-AM-3-Task1

frontend/src/components/Login.vue, frontend/src/components/RegisterForm.vue, frontend/src/components/book.vue, frontend/src/components/main.vue
Login/Logout
Mostrar nom usuari
Navegació Register->Login->Home
=> Tech debt 3

backend/app.py, backend/model/library.py, backend/tests/test_AM_3.py, backend/tests/test_BIB_2.py
En canvi de nomes isbn. Tambe s'han readaptat els testos unitaris perque segueixin aquesta informacio.
=> Modficacio per retornar les entrades de biblioteca com a json.

frontend/src/components/book.vue, frontend/src/components/main.vue
La cerca es fa correctament i amb un click et redirigeix al llibre escollit entre les opcions de la cerca parcial.
=> US-SRC-1-Task2

backend/app.py, frontend/src/components/book.vue, frontend/src/components/main.vue, frontend/src/main.js, frontend/src/router/index.js
Fixes at history mode and update (merge with dev) backend of the branch.
=> Tech debt 2 

backend/init_app.py, backend/model/recovery.py, backend/model/users.py, backend/resources/recovery.py, backend/tests/test_LR_3.py
Tambe s'ha afegit una nateja de entrades caducades.
=> Implementacio de l'endpoint per comprovar validesa de una key.

backend/app.py, backend/init_app.py, backend/model/recovery.py, backend/model/transactions.py, backend/resources/recovery.py, backend/resources/transactions.py, backend/tests/base_test.py, backend/tests/test_LR_3.py, backend/utils/mail.py
- Restructuracio del mail perque sigui similar a la db.
- Implementacio de un unit test per comprovar la validessa del correu.
- Modificacio del model transaction per evitar crida inecesaria al metode json().
=> Implementacio Endpoint recuperacio de correu + Millores de QA.

backend/app.py, backend/init_app.py, backend/model/recovery.py, backend/model/transactions.py, backend/model/users.py, backend/resources/recovery.py, backend/resources/transactions.py, backend/tests/base_test.py, backend/tests/test_LR_3.py, backend/utils/mail.py
Menciono que m'he equivocat i he treballat des de la branca de la tasca 2. No haura d'afectar en el merge pero recomano que revisis abans l'altre pull request.
=>  Implementacio de put per modificar contrasenya.

backend/init_app.py, backend/resources/transactions.py, backend/tests/test_COM_6.py
get transactions d'un usuari registrat
=> US-COM-6-Task6

backend/init_app.py, backend/resources/books.py, backend/resources/library.py, backend/tests/test_SRC_1.py
Per ara la funció like per buscar strings semblants no funciona. Només strings coincidents. Ja revisaré més endavant però així els de frontend poden anar treballant.
La prioritat és isbn > titol > autor > editorial. 
Això vol dir que si hi ha dos camps, per exemple isbn i autor, només busca per isbn. Ho milloraré però no sé si em donarà temps per aquest sprint.
=> Us src 1 task1

frontend/src/components/Search.vue, frontend/src/router/index.js
=> US-SRC-1-Task4

frontend/src/components/AddBooks.vue, frontend/src/components/Biblioteca.vue, frontend/src/components/DeleteBooks.vue, frontend/src/components/Login.vue, frontend/src/components/MisPedidos.vue, frontend/src/components/ModifyBooks.vue, frontend/src/components/PayMethod.vue, frontend/src/components/RegisterForm.vue, frontend/src/components/Search.vue, frontend/src/components/book.vue, frontend/src/components/changePassword.vue, frontend/src/components/main.vue, frontend/src/components/resetPassword.vue, frontend/src/components/subcomponents/navbar.vue
S'ha inclos el navbar modular i remplaçat el vell en totes les pàgines.
S'ha gestionat que el cart es mostres o no quan s'està loguejat o no.
S'ha gestionat amagar el contingut de les pàgines quan el carrito s'activa.
S'ha afegit un link a home.
S'ha afegit opcions al dropdown per poder accedir a afegir/modificar/eliminar.
#109
=> Tech debt 8 task3 navbar

backend/model/books.py, backend/model/reviews.py, backend/model/users.py, backend/tests/test_REV_3.py
Desenvolupament del model necesari a DB per gestionar les reviews i les puntuacions dels llibres. #111
=> US-REV-3-Task2

frontend/src/App.vue, frontend/src/components/Biblioteca.vue, frontend/src/components/MisPedidos.vue, frontend/src/components/PayMethod.vue, frontend/src/components/Search.vue, frontend/src/components/Stock.vue, frontend/src/components/book.vue, frontend/src/components/main.vue, frontend/src/components/subcomponents/foot.vue, frontend/src/router/index.js
* Footer modular añadido a las páginas necesarias.
* Retoques a ciertas páginas para que el footer se mántenga abajo.
=> [TECH-DEBT-8-Task2] Components modulars: footer

backend/init_app.py, backend/model/reviews.py, backend/resources/reviews.py, backend/tests/test_REV_3.py
=> Us rev 3 task3

backend/init_app.py, backend/tests/test_BIB_1.py
Causara confusio sino amb el endpoint de modificar estat de una entrada.
=> Correcio del endpoint de arxivar.

backend/init_app.py, backend/resources/library.py, backend/tests/test_BIB_2.py, backend/tests/test_BIB_3.py, backend/tests/test_REV_3.py
- Restructuracio dels endpoint del post perque segueixi els principis REST. LibraryEntry pasa a ser el recurs per una entrada i Library el de un llistat. (Proposta ja comentada al encarregat del front)
- Correcio derrer test REV 3, li faltava una tabulacio.
- Refractoring de comprovacions comunes de tots els recursus del endpoint de library
=> [US-BIB-3-Task2] Implementacio del endpoint PUT de library + Millores.

backend/model/books.py, backend/model/users.py, backend/resources/books.py, backend/resources/users.py, backend/tests/test_REV_1.py
#108 
S'han modificat els endpoints de GET a:
- /book/{isbn}
- /books
- /search
Ara accepten els paràmetres:
- reviews(bool): True per retornar també les reviews de cada llibre retornat, per defecte False/None.
- score(bool): True per retornar també la puntuació (1-5) de cada llibre retornat, per defecte False/None.
S'han modificat els endpoints de GET a:
- /user/{email}
Ara accepten els paràmetres:
- reviews(bool): True per retornar també les reviews que ha realitzat el usuari, per defecte False/None.
=> US-REV-1-Task3

frontend/src/components/Search.vue, frontend/src/components/book.vue, frontend/src/components/main.vue
S'ha afegit la visualització del score a:
- Homepage
- Search
- Book
=> US-REV-1-TASK2 Visualització del score 

frontend/src/components/book.vue
=> US-REV-1-Task1 Show reviews in book page

frontend/src/components/Biblioteca.vue, frontend/src/components/Login.vue, frontend/src/components/MisPedidos.vue, frontend/src/components/PayMethod.vue, frontend/src/components/RegisterForm.vue, frontend/src/components/Search.vue, frontend/src/components/Stock.vue, frontend/src/components/book.vue, frontend/src/components/changePassword.vue, frontend/src/components/main.vue, frontend/src/components/resetPassword.vue, frontend/src/components/subcomponents/AddBooks.vue, frontend/src/components/subcomponents/DeleteBooks.vue, frontend/src/components/subcomponents/ModifyBooks.vue, frontend/src/components/subcomponents/navbar.vue, frontend/src/main.js
=> Tech debt 14

frontend/package-lock.json, frontend/src/components/Biblioteca.vue, frontend/src/components/PayMethod.vue
*Dropdown añadido a los libros de la biblioteca
*Implementados las principales funciones para cambiar el estado de los libros
=> [US-BIB-3-Task1] Dropdown para cambiar de estado los libros de la biblioteca

backend/model/transactions.py, backend/tests/test_COM_6.py
Cada cop que un usuari fa una transaction, s'afegeix el llibre a la llibreria de l'usuari. Si el llibre ja hi era, no s'afegeix.
=> TECH-DEBT-9-Task3

frontend/src/components/Wishlist.vue, frontend/src/components/book.vue, frontend/src/components/subcomponents/navbar.vue, frontend/src/router/index.js
* WishList añadida al frontend de la página.
* Añadidos al frontend las funcionalidades necesarias para el correcto funcionamiento de la WishList
=> [US-COM-2-Task1] WishList

backend/init_app.py, backend/model/transactions.py, backend/resources/books.py, backend/tests/test_ESCP_3.py
Afegiré uns quants tests més després si puc
=> US-ESCP-3-Task2

backend/tests/test_GP_1.py
Ja estava fet, només he afegit un test per comprovar que funcionava.
=> US-GP-1-Task2

frontend/src/components/Biblioteca.vue
* Implementada la funcionalidad de búsqueda en biblioteca.
=> [US-BIB-6-Task1] Buscar en biblioteca

frontend/src/components/MisPedidos.vue
Rework visuals mis pedidos.
Related issues #187
=> Rework visuals mis pedidos

frontend/src/components/Biblioteca.vue
* Aplicados distintos filtros para poder buscar en biblioteca.
=> [US-BIB-5-Task1] Ordenar Biblioteca

backend/init_app.py, backend/model/reviews.py, backend/resources/reviews.py, backend/tests/test_US_GRR_3.py
Afegir el email en el json que retorna None en cas de que l'usuari se hagi donat de baixa.
Endpoint Actual: `DELETE /review/email/<string:email>/<int:isbn>`
@gmolinga: Dubte en el endpoint prefreixes que passar el id ja que el tens en json i aixi unific l'endpoint o tenir un endpoint per email i un per id. En plan `DELETE /review/email/<int:user_id>/<int:isbn>`
=> [US-GRR-3-Task2] Implementacio del endpoint de delete de reveiws des de user.

backend/model/users.py, frontend/src/components/Login.vue, frontend/src/components/book.vue
- GET USER ara també retorna la id del usuari i es guarda en cache.
- Un usuari pot eliminar les seves propies reviews des de book.
- Eliminar una review requereix confirmar un dialog de confirmació.
=> [US-GRR-3-Task1] Client eliminar review

backend/resources/reviews.py, backend/tests/test_US_GRR_1.py, backend/tests/test_US_GRR_3.py
Admin pot eliminar qualsevol review en l'endpoint de `DELETE /review/<int:user_id>/<int:isbn>`.
=> [US-GRR-1-Task2] Modificacio del endpoint delete.

backend/model/reviews.py, backend/resources/reviews.py, backend/tests/test_US_GRR_2.py
- El put te el mateix endpoint que el delete `PUT /review/<int:user_id>/<int:isbn>`.
- Creacio del metode generic update en tots dos models, on es pot modificar tot menys la PK.
=> [US-GRR-2-Task2] Creacio put review + metode update en el model review i score.

frontend/src/components/book.vue
- Admin pot eliminar qualsevol review a la pàgina book. 
Related issue #186 .
=> [US-GRR-1-Task1] Admin eliminar qualsevol review

backend/model/transactions.py, backend/resources/transactions.py, backend/tests/test_COM_8.py
Es pot no filtrar, filtrar per isbn, per user_id o per data (asc, desc). També es pot filtrar per qualsevol combinació dels filtres anteriors.
=> US-COM-8-Task2

frontend/src/components/RegisterForm.vue, frontend/src/components/subcomponents/navbar.vue
*Añadida la notificación de envio de correo en la pestaña de registro
=> [US-LR-4-Task1] Confirmación por correo

frontend/src/components/Biblioteca.vue
* Solucionado el problema de get y puts.
* Sustituidos los metodos para marcar los estados con 'axios.all'.
=> [HOT-FIX-3] Solucionado el problema de get y puts

backend/model/transactions.py, backend/resources/transactions.py, backend/tests/test_COM_8.py
Set changet to OrderedSet.
Added some more tests
=> hotfix-4-Filter by isbn returns all transactions that contain the book

backend/resources/books.py, backend/tests/test_AM_4.py
Put modify atr vendible. Must be an admin
=> TECH-DEBT-18-Task2

backend/model/recovery.py, backend/model/users.py
#204
No he pogut provar si arreglen el problema debut a no tenir tests en postgres. En fer el merge ho provare a traves de https://grup-es-dev.herokuapp.com/
=> [TECH-DEBT-17] Possible correcions del postgress

backend/model/transactions.py, backend/tests/test_COM_6.py
If it was in the wish list, change type to bought.
If it wasnt in the wish list, enter it to the library as bought
=> TECH-DEBT-19 - Delete book from wishlist

backend/model/transactions.py
=> [US-COM-6-Task3-2] Canvi del correu perquè no enviï un llistat de JSON pel correu, 

frontend/src/components/NotFound.vue, frontend/src/router/index.js
Controlem les urls not found enviant-les a la pagina custom de not found.
=> HotFix URL not found
